alert("Bem-vindo a seguir pediremos que informe alguns dados")
var nome=prompt("Informe seu nome")
var idade=prompt("Informe sua idade")
confirm("Sua idade é "+idade+"?")
alert("Nome: "+nome+" Idade: "+idade)